# Generated by Django 4.2.11 on 2024-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pais', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
    ]
