# Generated by Django 4.2.11 on 2024-04-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genero', '0002_delete_genero_usuario'),
        ('Usuario', '0002_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='generos_favoritos',
            field=models.ManyToManyField(blank=True, to='Genero.genero'),
        ),
    ]
