# Generated by Django 4.2.11 on 2024-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('born_in', models.DateField()),
                ('died_in', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
