# Generated by Django 4.2.11 on 2024-04-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autor', '0002_autor_generos_alter_autor_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='generos',
            new_name='generos_autor',
        ),
    ]
