# Generated by Django 4.2.11 on 2024-04-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero_Usuario',
        ),
    ]
